apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-device-config
data:
  LOG_LEVEL: debug
  KAFKA_BROKERS: default-kafka:9092
  KAFKA_TOPIC: iot.devices.metrics
  KAFKA_CONSUMER_GROUP_ID: iot.devices.metric-ingesters
