apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iot-device
  name: iot-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-device
  template:
    metadata:
      labels:
        app: iot-device
    spec:
      containers:
        - name: iot-device
          image: martinnirtl/demos.kafka.iot-device:latest
          resources: {}
          envFrom:
            - configMapRef:
                name: iot-device-config
