apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-ingester
  name: metrics-ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-ingester
  strategy: {}
  template:
    metadata:
      labels:
        app: metrics-ingester
    spec:
      containers:
        - image: martinnirtl/demos.kafka.metrics-ingester:latest
          name: metrics-ingester
          resources: {}
          envFrom:
            - configMapRef:
                name: metrics-ingester-config
